// <auto-generated />
namespace ClubDomain.Classes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedcoursesandstudents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedcoursesandstudents));
        
        string IMigrationMetadata.Id
        {
            get { return "201908210445584_Added courses and students"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
