// <auto-generated />
namespace ClubDomain.Classes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seeded3rdClub : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seeded3rdClub));
        
        string IMigrationMetadata.Id
        {
            get { return "201907220220345_seeded 3rd Club"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
